services:
  obs-intel:
    profiles: ["intel"]
    image: ghcr.io/dilllxd/obs-distroav:intel
    container_name: obs-intel
    network_mode: host
    devices:
      - /dev/dri
    group_add:
      - video
    shm_size: 512m
    volumes:
      - ./obs-config:/root/.config/obs-studio
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD:-}
      - RESOLUTION=${RESOLUTION:-1920x1080}
      - DEBUG=${DEBUG:-0}
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x obs >/dev/null && curl -fsS http://localhost:6081/ >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  obs-amd:
    profiles: ["amd"]
    image: ghcr.io/dilllxd/obs-distroav:amd
    container_name: obs-amd
    network_mode: host
    devices:
      - /dev/dri
    group_add:
      - video
    shm_size: 512m
    volumes:
      - ./obs-config:/root/.config/obs-studio
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD:-}
      - RESOLUTION=${RESOLUTION:-1920x1080}
      - DEBUG=${DEBUG:-0}
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x obs >/dev/null && curl -fsS http://localhost:6081/ >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  obs-nvidia:
    profiles: ["nvidia"]
    image: ghcr.io/dilllxd/obs-distroav:nvidia
    container_name: obs-nvidia
    network_mode: host
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu, compute, utility, video]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility,graphics
      - VNC_PASSWORD=${VNC_PASSWORD:-}
      - RESOLUTION=${RESOLUTION:-1920x1080}
      - DEBUG=${DEBUG:-0}
    shm_size: 512m
    volumes:
      - ./obs-config:/root/.config/obs-studio
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x obs >/dev/null && curl -fsS http://localhost:6081/ >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
