services:
  obs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obs-container
    network_mode: host
    devices:
      - /dev/dri
    group_add:
      - video
    shm_size: 512m
    volumes:
      - ../obs-config:/root/.config/obs-studio
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x obs >/dev/null && curl -fsS http://localhost:6081/ >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
