name: Build and Publish Images

on:
  push:
    branches: [ main ]
    paths:
      - 'intel/**'
      - 'amd/**'
      - 'nvidia/**'
      - '.github/workflows/build.yml'
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dilllxd/obs-distroav

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vendor: [intel, amd, nvidia]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.vendor }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.vendor }}
          file: ${{ matrix.vendor }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.vendor }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
